version: "3.7"

services: 
  database_bethehero:
    image: postgres
    container_name: database_bethehero
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=bethehero
      - POSTGRES_DB=bethehero
    volumes: 
      - pgdata:/data/postgres

  app:
    build: .
    container_name: bethehero
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/project02
    links: 
      - database_bethehero
    depends_on: 
      - database_bethehero

volumes: 
  pgdata:
    driver: local